FROM rust:1.81-bullseye # use gcc 2.31 is the same as P18

RUN apt-get update && apt-get install -y gcc-arm-linux-gnueabihf python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install maturin
RUN rustup target add armv7-unknown-linux-gnueabihf
WORKDIR /build
COPY . .
RUN mkdir -p .cargo && printf '[target.armv7-unknown-linux-gnueabihf]\nlinker = "arm-linux-gnueabihf-gcc"\n' > .cargo/config.toml

CMD ["maturin", "build", "--features", "python", "--release", "--target", "armv7-unknown-linux-gnueabihf", "--manylinux", "2_31", "-i", "3.9", "--out", "/build/dist"]
